<a href="https://colab.research.google.com/github/thewilzman/Area-calculator-program/blob/main/CP1AMAT240.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

np.set_printoptions(precision=6)

In [16]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix A:\n",A)
print("Matrix B:\n",B)


Matrix A:
 [[1 2]
 [3 4]
 [5 6]]
Matrix B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
x = np.array([4, 3, 2])
X = np.array([[1], [2], [3]])
print("Row vector x:\n",x)

print("Column vector X:")
print(X)

Row vector x:
 [4 3 2]
Column vector X:
[[1]
 [2]
 [3]]


In [11]:
print("Shape of A\n",A.shape)
print("Shape of B\n",B.shape)
print("Shape of x\n",x.shape)
print("Shape of X\n", X.shape)

Shape of A
 (3, 2)
Shape of B
 (3, 3)
Shape of x
 (3,)
Shape of X
 (3, 1)


In [12]:
a22 = A[1, 1]
print("A[1, 1] = a22:", a22)

A[1, 1] = a22: 4


In [13]:
firstRowB = B [0, :]
secondColB = B[:, 1]
print("First row of B:", firstRowB)
print("Second column of B:", secondColB)

First row of B: [1 2 3]
Second column of B: [2 5 8]


In [14]:
I3 = np.eye(3)
zeros3d = np.zeros(3)
zeros3x2 = np.zeros((3,2))
ones3x4 = np.ones((3,4))
diagonal4x4 = np.diag([1,2,3,4])
print("3x3 Identity:")
print(I3)
print("3D vector of zeros:")
print(zeros3d)
print("3x2 matrix of zeros:")
print(zeros3x2)
print("3x4 matrix of ones:")
print(ones3x4)
print("4x4 diagonal matrix:")
print(diagonal4x4)

3x3 Identity:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3D vector of zeros:
[0. 0. 0.]
3x2 matrix of zeros:
[[0. 0.]
 [0. 0.]
 [0. 0.]]
3x4 matrix of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
4x4 diagonal matrix:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [18]:
y = np.random.uniform(0, 1, 3)
z = np.random.uniform(0, 1, 3)
print("Vector y:", y)
print("Vector z:", z)
print("y + z:", y + z)
print("6y:", 6 * y)

C = np.random.uniform(0, 1, (3,3))
D = np.random.uniform(0, 1, (3,3))
print("Matrix C:\n",C)
print("Matrix D:\n",D)
print("C - D:\n",C-D)
print("4C:", 4*C)


Vector y: [0.57749  0.781901 0.106503]
Vector z: [0.279394 0.439598 0.862364]
y + z: [0.856884 1.221499 0.968867]
6y: [3.464942 4.691405 0.639021]
Matrix C:
 [[0.741292 0.078552 0.468643]
 [0.015232 0.378594 0.472476]
 [0.317829 0.753677 0.340307]]
Matrix D:
 [[0.296036 0.366734 0.138354]
 [0.096462 0.038092 0.995395]
 [0.435775 0.634486 0.602815]]
C - D:
 [[ 0.445256 -0.288182  0.33029 ]
 [-0.081231  0.340502 -0.522919]
 [-0.117945  0.119191 -0.262509]]
4C: [[2.965167 0.314209 1.874574]
 [0.060927 1.514377 1.889904]
 [1.271317 3.014708 1.361227]]


In [19]:
dotProductYZ = np.dot(y, z)
normY = np.linalg.norm(y)
print("Dot Product y .z :\n", dotProductYZ)
print("Norm of y:\n", normY)

Dot Product y .z :
 0.5969136021459734
Norm of y:
 0.977858384452492


In [21]:
Acol =  np.array([[1], [2], [3], [1]])
Brow = np.array([[-1, 2, 1, 4]])
AB = np.dot(Acol, Brow)
BA = np.dot(Brow, Acol)
AB10 = np.linalg.matrix_power(AB, 10)

print("AB:\n",AB)
print("BA:\n",BA)
print("(AB)^10:\n",AB10)


AB:
 [[-1  2  1  4]
 [-2  4  2  8]
 [-3  6  3 12]
 [-1  2  1  4]]
BA:
 [[10]]
(AB)^10:
 [[-1000000000  2000000000  1000000000  4000000000]
 [-2000000000  4000000000  2000000000  8000000000]
 [-3000000000  6000000000  3000000000 12000000000]
 [-1000000000  2000000000  1000000000  4000000000]]


For calculating manually (AB)^10 without a computer, we know that (AB)^10= A*(BA)^9 *B
rank -1 exploit: AB has only one independent row, so powers don't grow complexity, they just scale.
